version: '3.8'

services:
  website-monitor:
    # build: .
    image: website-monitor:latest
    pull_policy: never
    container_name: website-change-monitor
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/data:/app/server/data
